<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ReportMonth.aspx.cs" Inherits="Fuel_Management.ReportWeek1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Monthly Report</h1>
                </div>
                <!-- /.col-lg-12 -->
           
            
               
							<div>
                                
                                <asp:GridView ID="gvFuelManagement" DataKeyNames="Code" Width="67%"
                                    AutoGenerateColumns="false" AutoGenerateEditButton="true" ShowHeaderWhenEmpty="true"
                                    AutoGenerateDeleteButton="true" runat="server"
                                    BackColor="White" BorderColor="#DEDFDE" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" BorderStyle="None" Height="497px">
                                    <AlternatingRowStyle BackColor="White"></AlternatingRowStyle>

                                    <Columns>
                                        <asp:TemplateField HeaderText="Site ID">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("siteID")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="siteID" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Cluster">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("Cluster")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="cluster" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Region">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("region")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="region" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Actual Date Refueled">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("ADrefueled")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="actualDateR" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Level before">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("Levelbefore")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="Levelbefore" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Level After">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("Levelafter")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="Levelafter" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Actual fuel delivered by truck">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("AFDT")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="AFDBT" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                         <asp:TemplateField HeaderText="Receipt Number">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("ReceiptNumber")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="receiptNumber" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Cycle Volume">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("CycleVolume")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="cycleVolume" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="First Top Up Volume">
                                            <ItemTemplate>
                                                <asp:Label Text='<%#Eval("FirstTopupVolume")%>' runat="server" />
                                            </ItemTemplate>
                                            <EditItemTemplate>
                                                <asp:TextBox ID="cycleVolume" runat="server" />
                                            </EditItemTemplate>
                                        </asp:TemplateField>
                                         


                                        

                                    </Columns>





                                    <FooterStyle BackColor="#CCCC99"></FooterStyle>

                                    <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White"></HeaderStyle>

                                    <PagerStyle HorizontalAlign="Right" BackColor="#F7F7DE" ForeColor="Black"></PagerStyle>

                                    <RowStyle BackColor="#F7F7DE"></RowStyle>

                                    <SelectedRowStyle BackColor="#CE5D5A" ForeColor="White" Font-Bold="True"></SelectedRowStyle>

                                    <SortedAscendingCellStyle BackColor="#FBFBF2"></SortedAscendingCellStyle>

                                    <SortedAscendingHeaderStyle BackColor="#848384"></SortedAscendingHeaderStyle>

                                    <SortedDescendingCellStyle BackColor="#EAEAD3"></SortedDescendingCellStyle>

                                    <SortedDescendingHeaderStyle BackColor="#575357"></SortedDescendingHeaderStyle>
                                </asp:GridView>

                                

							</div>
                             
                            
                          
                
            </div>
            <!-- /.row -->
</asp:Content>
